### ISSUE TITLE
Not implemented `chain_id` function.

### ISSUE THREAD

**Issue by smiasojed** [paritytech/revive#44] opened 2024-09-12 09:30 UTC
The ERC20 workspace in Remix is failing to compile.
## How to reproduce:
1. Got to https://smiasojed.github.io/remix-project
2. Select ERC20 workspace
3. Compile

results:
```
Contract `contracts/MyToken.sol:MyToken` compiling error: thread 'main' panicked at /home/runner/work/revive/revive/crates/llvm-context/src/polkavm/evm/context.rs:46:5:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
eip: https://eips.ethereum.org/EIPS/eip-1344

**Comment by xermicus** [comment] 2024-09-12 09:39
Can you rebase against latest `main` where it will always return a chain id of 0 instead of panicking? I [snuck it in](https://github.com/xermicus/revive/blob/main/crates/llvm-context/src/polkavm/evm/context.rs#L46) recently. We still have to agree on those.

**Comment by smiasojed** [comment] 2024-09-18 11:17
With new version I got panic:
Contract `contracts/MyToken.sol:MyToken` compiling error: thread 'main' panicked at /Users/smiasojed/Development/revive/crates/llvm-context/src/polkavm/context/pointer.rs:65:9:\nassertion `left != right` failed: Stack pointers cannot be addressed\n  left: Stack\n right: Stack\n

**Comment by xermicus** [comment] 2024-09-18 11:39
Can you provide me the contents of `MyToken.sol`? I don't see the `ERC20` workspace you mentioned originally

**Comment by xermicus** [comment] 2024-09-18 11:40
Also any libraries, assuming it uses OZ

**Comment by xermicus** [comment] 2024-09-18 11:41
Nevermind. It is caused by the immutables, which are still a WIP.

**Comment by smiasojed** [comment] 2024-09-18 11:50
> Can you provide me the contents of `MyToken.sol`? I don't see the `ERC20` workspace you mentioned originally
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol";

contract MyToken is ERC20, ERC20Permit {
    constructor() ERC20("MyToken", "MTK") ERC20Permit("MyToken") {}
}
```

**Comment by xermicus** [comment] 2024-09-18 14:24
I planned to add it to the pallet as configuration. Eventually we'll have to settle on the ChainID for every chain we deploy, including testnets. So having it in the configuration seems reasonable to me.

**Comment by athei** [comment] 2024-09-18 14:30
One obvious idea would be to use the parachain id. But it is not unique across relay chains. So maybe something like `keccak(relay_chain_id ++ parachain_id). But no matter what we pick: Exposing it as `Config` item is the way to go as it has to be configured by the runtime.

**Comment by xermicus** [comment] 2024-09-18 14:56
Yeah, we might want to add them [here](https://github.com/ethereum-lists/chains) too.

**Comment by athei** [comment] 2024-09-18 15:30
Yes I was wondering how if numbers are coordinated. So basically just pick a unique one and get a PR merged. No hashing required :)

**Closed** 2024-09-24 07:14 UTC
